decode_env_PKG         = 																																	\
	+incdir+$(UVMF_VIP_LIBRARY_HOME)/environment_packages/decode_env_pkg 										\
	$(UVMF_VIP_LIBRARY_HOME)/environment_packages/decode_env_pkg/decode_env_pkg.sv 					\

comp_decode_env_pkg:
	vlog -sv $(decode_env_PKG)
